# ç»‘å®šçš„åŸŸå
baseURL = "https://xyming108.github.io/"

# en-us
languageCode = "zh-cn"

title = "Sulv's Blog"

# ä¸»é¢˜åå­—ï¼Œå’Œthemesæ–‡ä»¶å¤¹ä¸‹çš„ä¸€è‡´
theme = "hugo-PaperMod"

enableInlineShortcodes = true
enableEmoji = true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT = true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
hasCJKLanguage = true # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡ å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯

buildDrafts = false
buildFuture = false
buildExpired = false

# è°·æ­Œç»Ÿè®¡
googleAnalytics = ""

# Copyright: Sulv

paginate = 15    # é¦–é¡µæ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
summaryLength = 140 # æ–‡ç« æ¦‚è§ˆçš„è‡ªå­—æ•°ï¼Œé»˜è®¤70

[minify]
  disableXML = true
  # minifyOutput = true

[permalinks] # è®¿é—®åšå®¢æ—¶ç½‘å€çš„æ˜¾ç¤ºå½¢å¼
  post = "/:title/"
  # post = "/:year/:month/:day/:title/"

defaultContentLanguage = "en" # æœ€é¡¶éƒ¨é¦–å…ˆå±•ç¤ºçš„è¯­è¨€é¡µé¢
defaultContentLanguageInSubdir = true

[languages]

  [languages.en]
    languageName = "English"
    weight = 1

    [languages.en.profileMode]
      enabled = true
      title = "(ã€ƒ'â–½'ã€ƒ)"
      subtitle = ""
      # subtitle = "ğŸ§¨å­¦è€Œæ—¶ä¹ ä¹‹ï¼Œä¸äº¦è¯´ä¹ï¼Ÿæœ‰æœ‹è‡ªè¿œæ–¹æ¥ï¼Œä¸äº¦ä¹ä¹ï¼Ÿ<br/>ğŸ‘‡è”ç³»æ–¹å¼"
      imageUrl = "img/Q.gif"
      imageTitle = ""
      imageWidth = 150
      imageHeight = 150

      [[languages.en.profileMode.buttons]]
        name = "ğŸ§± å»ºç«™"
        url = "posts/blog"

      [[languages.en.profileMode.buttons]]
        name = "ğŸ‘¨ğŸ»â€ğŸ’» æŠ€æœ¯"
        url = "posts/tech"

      [[languages.en.profileMode.buttons]]
        name = "ğŸ“• é˜…è¯»"
        url = "posts/read"

      [[languages.en.profileMode.buttons]]
        name = "ğŸ– ç”Ÿæ´»"
        url = "posts/life"

    [[languages.en.menu.main]]
      identifier = "search"
      name = "ğŸ” æœç´¢"
      url = "search"
      weight = 1

    [[languages.en.menu.main]]
      identifier = "home"
      name = "ğŸ  ä¸»é¡µ"
      url = "/"
      weight = 2

    [[languages.en.menu.main]]
      identifier = "posts"
      name = "ğŸ“š æ–‡ç« "
      url = "posts"
      weight = 3

    [[languages.en.menu.main]]
      identifier = "tags"
      name = "ğŸ§© æ ‡ç­¾"
      url = "tags"
      weight = 15

    [[languages.en.menu.main]]
      identifier = "archives"
      name = "â±ï¸ æ—¶é—´è½´"
      url = "archives/"
      weight = 20

    [[languages.en.menu.main]]
      identifier = "about"
      name = "ğŸ™‹ğŸ»â€â™‚ï¸ å…³äº"
      url = "about"
      weight = 50

    [[languages.en.menu.main]]
      identifier = "links"
      name = "ğŸ¤ å‹é“¾"
      url = "links"
      weight = 60

[outputs]
  home = ["HTML", "RSS", "JSON"]

# è¿™é‡Œçš„å‚æ•°ä¼šè¢«ä»£ç ä»¥ .Site.Params çš„å½¢å¼è¯»å–
[params]
  env = "production" # to enable google analytics, opengraph, twitter-cards and schema.
  description = ""
  author = "Sulv"
  # author = ["Me", "You"] # multiple authors

  defaultTheme = "auto"  # defaultTheme: light or  dark
  disableThemeToggle = false
  DateFormat = "2006-01-02"
  ShowShareButtons = true
  ShowReadingTime = true
  # disableSpecialistPost = true
  displayFullLangName = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  hideFooter = false # éšè—é¡µè„š
  ShowWordCounts = true
  VisitCount = true
  ShowLastMod = true #æ˜¾ç¤ºæ–‡ç« æ›´æ–°æ—¶é—´

  ShowToc = true # æ˜¾ç¤ºç›®å½•
  TocOpen = true # è‡ªåŠ¨å±•å¼€ç›®å½•

  comments = true
  # ç¤¾äº¤å›¾æ ‡
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/xyming108"
  [[params.socialIcons]]
    name = "twitter"
    url = "img/twitter.png"
  [[params.socialIcons]]
    name = "facebook"
    url = "https://www.facebook.com/profile.php?id=100027782410997"
  [[params.socialIcons]]
    name = "instagram"
    url = "img/instagram.png"
  [[params.socialIcons]]
    name = "QQ"
    url = "img/qq.png"
  [[params.socialIcons]]
    name = "WeChat"
    url = "img/wechat.png"
  [[params.socialIcons]]
    name = "bilibili"
    url = "https://space.bilibili.com/234461224"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:1931559710@qq.com"
  [[params.socialIcons]]
    name = "RSS"
    url = "index.xml"

  # å·¦ä¸Šè§’å›¾æ ‡
  [params.label]
    text = "Sulv's Blog"
    icon = "img/Q.gif"
    iconHeight = 35

  [params.analytics.google]
    SiteVerificationTag = ""

  [params.assets]
    favicon = "img/Q.gif"
    favicon16x16 = "img/Q.gif"
    favicon32x32 = "img/Q.gif"
    apple_touch_icon = "img/Q.gif"
    safari_pinned_tab = "img/Q.gif"

  [params.cover]
    hidden = false # hide everywhere but not in structured data
    hiddenInList = false # hide on list pages and home
    hiddenInSingle = false # hide on single page

  [params.fuseOpts] # æœç´¢é…ç½®
    isCaseSensitive = false
    shouldSort = true
    location = 0
    distance = 1000
    threshold = 0.4
    minMatchCharLength = 0
    keys = [ "title", "permalink", "summary" ]

  StartYear = 2020 # åº•éƒ¨å¼€å§‹å¹´ä»½
  FilingNo = "å¡«å†™è‡ªå·±çš„å¤‡æ¡ˆå·" # åº•éƒ¨å¤‡æ¡ˆå·
  PublicSecurityIconLink = "å¡«è‡ªå·±çš„å…¬å®‰å›¾æ ‡é“¾æ¥" # å¡«è‡ªå·±çš„å…¬å®‰å›¾æ ‡é“¾æ¥,å¯ç”¨ç»å¯¹è·¯å¾„ï¼Œç›¸å¯¹è·¯å¾„å¦‚ img/beian.png
  PublicNetworkSecurity = "å¡«è‡ªå·±çš„å…¬ç½‘å®‰å¤‡" # åº•éƒ¨å…¬ç½‘å®‰å¤‡å·

  Reward = true #æ‰“èµæ˜¯å¦å¼€å¯
  # æ‰“èµå¾®ä¿¡å›¾ç‰‡åœ°å€ï¼Œ
  # å¯ç”¨ç»å¯¹å’Œç›¸å¯¹åœ°å€ï¼Œç›¸å¯¹åœ°å€çš„å›¾ç‰‡éœ€æ”¾åœ¨static/imgä¸‹ï¼Œ
  # å¡«å†™æ ¼å¼ä¸ºimg/wechat_pay.png
  WechatPay = "img/wechat_pay.png"
  Alipay = "img/alipay.png" #æ‰“èµæ”¯ä»˜å®å›¾ç‰‡åœ°å€

  # twikooè¯„è®º
  [params.twikoo]
    version = "1.5.8" # å¡«å†™twikooç‰ˆæœ¬å·
    id = ""  # å¡«å†™è‡ªå·±çš„twikoo id
    region = ""  # ç¯å¢ƒåœ°åŸŸï¼Œé»˜è®¤ä¸º ap-shanghaiï¼Œå¦‚æœæ‚¨çš„ç¯å¢ƒåœ°åŸŸä¸æ˜¯ä¸Šæµ·ï¼Œéœ€ä¼ æ­¤å‚æ•°ï¼Œè¯·çœ‹twikooå®˜æ–¹æ–‡æ¡£

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # HUGO é»˜è®¤è½¬ä¹‰ Markdown æ–‡ä»¶ä¸­çš„ HTML ä»£ç ï¼Œå¦‚éœ€å¼€å¯çš„è¯

  [markup.highlight]
    

markup:
  goldmark:
    renderer:
      unsafe: true # HUGO é»˜è®¤è½¬ä¹‰ Markdown æ–‡ä»¶ä¸­çš„ HTML ä»£ç ï¼Œå¦‚éœ€å¼€å¯çš„è¯
  highlight:
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    # lineNos: true
    noClasses: true
    tabWidth: 4
    style: monokai
    # codeFencesï¼šä»£ç å›´æ åŠŸèƒ½ï¼Œè¿™ä¸ªåŠŸèƒ½ä¸€èˆ¬éƒ½è¦è®¾ä¸º true çš„ï¼Œä¸ç„¶å¾ˆéš¾çœ‹ï¼Œå°±æ˜¯å¹²å·´å·´çš„-ä»£ç æ–‡å­—ï¼Œæ²¡æœ‰é¢œè‰²ã€‚
    # guessSyntaxï¼šçŒœæµ‹è¯­æ³•ï¼Œè¿™ä¸ªåŠŸèƒ½å»ºè®®è®¾ç½®ä¸º true, å¦‚æœä½ æ²¡æœ‰è®¾ç½®è¦æ˜¾ç¤ºçš„è¯­è¨€åˆ™ä¼šè‡ªåŠ¨åŒ¹é…ã€‚
    # hl_Linesï¼šé«˜äº®çš„è¡Œå·ï¼Œä¸€èˆ¬è¿™ä¸ªä¸è®¾ç½®ï¼Œå› ä¸ºæ¯ä¸ªä»£ç å—æˆ‘ä»¬å¯èƒ½å¸Œæœ›è®©é«˜äº®çš„åœ°æ–¹ä¸ä¸€æ ·ã€‚
    # lineNoStartï¼šè¡Œå·ä»ç¼–å·å‡ å¼€å§‹ï¼Œä¸€èˆ¬ä» 1 å¼€å§‹ã€‚
    # lineNosï¼šæ˜¯å¦æ˜¾ç¤ºè¡Œå·ï¼Œæˆ‘æ¯”è¾ƒå–œæ¬¢æ˜¾ç¤ºï¼Œæ‰€ä»¥æˆ‘è®¾ç½®çš„ä¸º true.
    # lineNumbersInTableï¼šä½¿ç”¨è¡¨æ¥æ ¼å¼åŒ–è¡Œå·å’Œä»£ç ,è€Œä¸æ˜¯ æ ‡ç­¾ã€‚è¿™ä¸ªå±æ€§ä¸€èˆ¬è®¾ç½®ä¸º true.
    # noClassesï¼šä½¿ç”¨ class æ ‡ç­¾ï¼Œè€Œä¸æ˜¯å†…åµŒçš„å†…è”æ ·å¼

[privacy]
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
        